/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Cars;
import Business.CarsDirectory;
import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sai
 */
public class AddCar extends javax.swing.JPanel {

    /**
     * Creates new form AddCar
     */
    private JPanel userProcessContainer;
    private CarsDirectory carsDirectory;

    AddCar(JPanel userProcessContainer, CarsDirectory carsDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carsDirectory = carsDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        txtBrandName = new javax.swing.JTextField();
        txtNumberOfSeats = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtYearOfManufacturing = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtExpirationDate = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAddCar = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setText("Model Number:");

        jLabel2.setText("Brand Name:");

        jLabel3.setText("Number Of Seats:");

        jLabel4.setText("Serial Number:");

        jLabel5.setText("Year of Manufacturing:");

        jLabel6.setText("Available Status:");

        jLabel7.setText("Expiration Date:");

        jLabel8.setText("Location:");

        jLabel9.setText("City:");

        txtBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandNameActionPerformed(evt);
            }
        });

        txtStatus.setEditable(false);

        txtExpirationDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpirationDateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Add Car");

        btnAddCar.setBackground(new java.awt.Color(204, 0, 204));
        btnAddCar.setText("Add Car");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 0, 255));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        checkBox.setText("Yes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(btnAddCar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txtBrandName)
                                .addComponent(txtNumberOfSeats)
                                .addComponent(txtSerialNumber)
                                .addComponent(txtYearOfManufacturing)
                                .addComponent(txtExpirationDate)
                                .addComponent(txtLocation)
                                .addComponent(txtCity)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(checkBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumberOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtYearOfManufacturing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAddCar)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandNameActionPerformed

    private void txtExpirationDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpirationDateActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_txtExpirationDateActionPerformed
    
     private boolean brandNamePatternCorrect(){
        Pattern p =Pattern.compile("^[a-zA-Z]+$");
        Matcher m = p.matcher(txtBrandName.getText());
        boolean b = m.matches();
        return b;
    }
    
    
    
    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        // TODO add your handling code here:
        String modelNumber = txtModelNumber.getText();
        String brandName = txtBrandName.getText();
        
        String serialNumber = txtSerialNumber.getText();
        
        //System.out.println("Hi"+jCalendar1.getCalendar().getTime());
        Date expirationDate = null;
        try {
             expirationDate = new SimpleDateFormat("dd/MM/yyyy").parse(txtExpirationDate.getText());
        } catch (ParseException ex) {
            System.out.println("Date failure");
        }
        String location = txtLocation.getText();
        String city = txtCity.getText();
        
        if(checkBox.isSelected()){
            txtStatus.setText("Y");
            
        }
        else{
            txtStatus.setText("N");
        }
        
        String status = txtStatus.getText();
        
         String specialCharacters=" !#$%&'()*+,-./:;<=>?@[]^_`{|}~";
          
          String str2[]=modelNumber.split("");

          int i = 0;
          for(Cars car : carsDirectory.getCarsDirectory()){
              System.out.println("abc"+ car.getSerialNumber());
              System.out.println("123"+ txtSerialNumber.getText());
              if(car.getSerialNumber().equalsIgnoreCase(txtSerialNumber.getText())){
                  i = 1;
                  System.out.println("Loop"+ i);
              }
          }
          
        System.out.println("Loop"+ i);
        try{
         int yearOfManufacturing = Integer.parseInt(txtYearOfManufacturing.getText());
         int numberOfSeats = Integer.parseInt(txtNumberOfSeats.getText());
         
         
         if(i==1){
             JOptionPane.showMessageDialog(null, "Please Select Unique Serial number");
         }
         else{
             
       
         if(modelNumber.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Model Number");
        }
        else{
            if(brandName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Brand Name");
        }
            else{
                if(serialNumber.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Serial Number");
        }
                else{
                    if(brandNamePatternCorrect()==false){
                        JOptionPane.showMessageDialog(null, "Brand Name should only contain Char");
                    }
                    else{
                        
                    
                    if(String.valueOf(expirationDate).isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Expiration Date");
            
        }
                    
                    else{
                        
                        
                        Cars cars = carsDirectory.addCars();
                        System.out.println(carsDirectory.getCarsDirectory().get(0).getModelNumber());
                        cars.setModelNumber(modelNumber);
                        cars.setBrandName(brandName);
                        cars.setNumberOfSeats(numberOfSeats);
                        cars.setSerialNumber(serialNumber);
                        cars.setYearOfManufacturing(yearOfManufacturing);
                        cars.setStatus(status);
                        cars.setExpirationDate(expirationDate);
                        cars.setLocation(location);
                        cars.setCity(city);
                        carsDirectory.setBrandNameDirectory(cars.getBrandName());
                        System.out.println("a");
                        System.out.println(carsDirectory.getCarsDirectory().get(0).getBrandName());
        
        
        JOptionPane.showMessageDialog(null, "Car added successfully.");
                    }
                    }
                }
            }
        }
         }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Year of Manufacturing and Number of seats should only be int");
           
        }
        
        
        
        
        
        
        
        
       
    }//GEN-LAST:event_btnAddCarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtNumberOfSeats;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtYearOfManufacturing;
    // End of variables declaration//GEN-END:variables
}
