/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Cars;
import Business.CarsDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sai
 */
public class CarsByYearPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarsByYearPanel
     */
    private JPanel userProcessContainer;
    private String txtYearOfManufacturing;
    private CarsDirectory carsDirectory;
    

    CarsByYearPanel(JPanel userProcessContainer, String txtYearOfManufacturing, CarsDirectory carsDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.txtYearOfManufacturing = txtYearOfManufacturing;
        this.carsDirectory = carsDirectory;
        
        populateCarsByYearTable();
    }

    
    public void populateCarsByYearTable(){
        DefaultTableModel tcb = (DefaultTableModel) tblCarsByYear.getModel();
        tcb.setRowCount(0);
        int s =0;
        
        for(Cars cars: carsDirectory.getCarsDirectory()){
            System.out.println(s);
            System.out.println(cars.getModelNumber());
            System.out.println(cars.getBrandName());
            System.out.println(cars.getSerialNumber());
            System.out.println(cars.getYearOfManufacturing());
            
            Object[] row =  new Object[4];
            row[0]= cars;
            row[1]=cars.getBrandName();
            row[2]=cars.getSerialNumber();
            row[3]=cars.getYearOfManufacturing();
            
            //tcb.addRow(row);
            if(txtYearOfManufacturing.equalsIgnoreCase(String.valueOf(cars.getYearOfManufacturing()))){
               tcb.addRow(row);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarsByYear = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 0));

        tblCarsByYear.setBackground(new java.awt.Color(153, 153, 255));
        tblCarsByYear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Model", "Serial Number", "Brand Name", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarsByYear);
        if (tblCarsByYear.getColumnModel().getColumnCount() > 0) {
            tblCarsByYear.getColumnModel().getColumn(0).setResizable(false);
            tblCarsByYear.getColumnModel().getColumn(1).setResizable(false);
            tblCarsByYear.getColumnModel().getColumn(2).setResizable(false);
            tblCarsByYear.getColumnModel().getColumn(3).setResizable(false);
        }

        btnBack.setBackground(new java.awt.Color(204, 0, 204));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarsByYear;
    // End of variables declaration//GEN-END:variables
}
