/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Cars;
import Business.CarsDirectory;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sai
 */
public class CarsByBrandPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarsByBrandPanel
     */
    private JPanel userProcessContainer;
    private String txtBrandName;
    private CarsDirectory carsDirectory; 

    CarsByBrandPanel(JPanel userProcessContainer, String txtBrandName, CarsDirectory carsDirectory) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.txtBrandName = txtBrandName;
       this.carsDirectory = carsDirectory;
       
       populateCarsByBrandTable();
    }
    
    public String toformat(Date date){
       SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
       String b = formatter.format(date);
       return b;
    }

     public void populateCarsByBrandTable(){
        DefaultTableModel tcb = (DefaultTableModel) tblCarsByBrand.getModel();
        tcb.setRowCount(0);
        int s =0;
        System.out.println("123");
        System.out.println(carsDirectory.getCarsDirectory().get(0).getModelNumber());
        System.out.println("Hash");
        System.out.println(carsDirectory.getBrandNameDirectory());
        System.out.println("Hash");
        for(Cars cars: carsDirectory.getCarsDirectory()){
            System.out.println(s);
            System.out.println(cars.getModelNumber());
            System.out.println(cars.getBrandName());
            System.out.println(cars.getSerialNumber());
            System.out.println(cars.getCity());
            
            Object[] row =  new Object[10];
            row[0]= cars;
            row[1]=cars.getBrandName();
            row[2]=cars.getNumberOfSeats();
            row[3]=cars.getSerialNumber();
            row[4]=cars.getYearOfManufacturing();
            row[5]=cars.getStatus();
            row[6]=toformat(cars.getExpirationDate());
            row[7]=cars.getLocation();
            row[8]=cars.getCity();
            row[9]=toformat(cars.getUpdatedOn());
            
            //tcb.addRow(row);
            if(txtBrandName.equalsIgnoreCase(cars.getBrandName())){
               tcb.addRow(row);
            }
            
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarsByBrand = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtCarsModel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 0));

        tblCarsByBrand.setBackground(new java.awt.Color(153, 153, 255));
        tblCarsByBrand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cars Model", "Brand Name", "No Of Seats", "Serial Number", "Manufactured year", "Status", "Expiration Date", "Location", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarsByBrand);
        if (tblCarsByBrand.getColumnModel().getColumnCount() > 0) {
            tblCarsByBrand.getColumnModel().getColumn(0).setResizable(false);
            tblCarsByBrand.getColumnModel().getColumn(1).setResizable(false);
            tblCarsByBrand.getColumnModel().getColumn(2).setResizable(false);
            tblCarsByBrand.getColumnModel().getColumn(3).setResizable(false);
            tblCarsByBrand.getColumnModel().getColumn(4).setResizable(false);
            tblCarsByBrand.getColumnModel().getColumn(5).setResizable(false);
            tblCarsByBrand.getColumnModel().getColumn(6).setResizable(false);
            tblCarsByBrand.getColumnModel().getColumn(7).setResizable(false);
            tblCarsByBrand.getColumnModel().getColumn(8).setResizable(false);
        }

        btnBack.setBackground(new java.awt.Color(204, 0, 204));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(204, 0, 204));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Cars Model");

        jLabel2.setText("City:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(btnSearch)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCarsModel)
                                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarsModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String modelNumber = txtCarsModel.getText();
        String city = txtCity.getText();
        
        SecondarySearchPanel searchpanel = new SecondarySearchPanel(userProcessContainer, tblCarsByBrand, carsDirectory, txtBrandName ,txtCarsModel.getText(), txtCity.getText());
        userProcessContainer.add("SecondarySearchPanel",searchpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarsByBrand;
    private javax.swing.JTextField txtCarsModel;
    private javax.swing.JTextField txtCity;
    // End of variables declaration//GEN-END:variables
}
