/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Cars;
import Business.CarsDirectory;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sai
 */
public class FleetCataloguePanel extends javax.swing.JPanel {

    /**
     * Creates new form FleetCataloguePanel
     */
   private JPanel userProcessContainer;
   private CarsDirectory carsDirectory;
   private Cars cars;
   

    FleetCataloguePanel(JPanel userProcessContainer, CarsDirectory carsDirectory, Cars cars) {
       initComponents();
       this.userProcessContainer =  userProcessContainer;
       this.carsDirectory = carsDirectory;
       this.cars = cars;
       
       
       populateFleetTable();
       //txtDateLatest.setText(String.valueOf(cars.getUpdatedOn()));
    }
        
    
    public void populateFleetTable(){
        DefaultTableModel tcb = (DefaultTableModel) tblFleet.getModel();
        tcb.setRowCount(0);
        Date dt = null;
        
        for(Cars cars: carsDirectory.getCarsDirectory()){
            
           
            Object[] row =  new Object[10];
            row[0]= cars;
            row[1]=cars.getBrandName();
            row[2]=cars.getNumberOfSeats();
            row[3]=cars.getSerialNumber();
            row[4]=cars.getYearOfManufacturing();
            row[5]=cars.getStatus();
            row[6]=toformat(cars.getExpirationDate());
            row[7]=cars.getLocation();
            row[8]=cars.getCity();
            row[9]=toformat(cars.getUpdatedOn());
            
           
            System.out.println(cars.getUpdatedOn()+"1");
               tcb.addRow(row);
            dt = cars.getUpdatedOn();
            System.out.println(cars.getUpdatedOn()+"2");
        }
       
     txtDate.setText(String.valueOf(dt));
     
     }
    
    public String toformat(Date date){
       SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
       String b = formatter.format(date);
       return b;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFleet = new javax.swing.JTable();
        txtDate = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 0));

        tblFleet.setBackground(new java.awt.Color(153, 153, 255));
        tblFleet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model Number", "Brand Name", "Number of Seats", "Serial Number", "Year Of Manufacturing", "Status", "Expiration Date", "Location", "City", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFleet);
        if (tblFleet.getColumnModel().getColumnCount() > 0) {
            tblFleet.getColumnModel().getColumn(0).setResizable(false);
            tblFleet.getColumnModel().getColumn(1).setResizable(false);
            tblFleet.getColumnModel().getColumn(2).setResizable(false);
            tblFleet.getColumnModel().getColumn(3).setResizable(false);
            tblFleet.getColumnModel().getColumn(4).setResizable(false);
            tblFleet.getColumnModel().getColumn(5).setResizable(false);
            tblFleet.getColumnModel().getColumn(6).setResizable(false);
            tblFleet.getColumnModel().getColumn(7).setResizable(false);
        }

        btnBack.setBackground(new java.awt.Color(204, 0, 204));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(430, 430, 430)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(688, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFleet;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
